### ISSUE TITLE
[BUG] Can not get relations (Tables) in v8.2.3

### ISSUE THREAD

**Issue by fonnebien** [cweijan/vscode-mysql#1474]
- Database type and version: CockroachDB v24.3.7

I'm receiving the following error when wanting to view Tables in VSCode.

`unknown function: pg_total_relation_size()`

**Comment by cweijan** [comment]
Sorry for this problem, please roll back to the old version first, I will fix it in the next version.

**Comment by fonnebien** [comment]
> Sorry for this problem, please roll back to the old version first, I will fix it in the next version.

Perfect, thank you for the quick response!

**Comment by cweijan** [comment]
Fixed in version 8.2.4.

**Comment by taylornoss** [comment]
I am still seeing this issue in version 8.2.4. Rolling back to 8.2.2 does not have the problem.

**Comment by fonnebien** [comment]
> I am still seeing this issue in version 8.2.4. Rolling back to 8.2.2 does not have the problem.

Negative on my end. The 8.2.4 patch solved the issue for me.

**Comment by cweijan** [comment]
@taylornoss Hello, please tell me the database and version you are using.

**Comment by taylornoss** [comment]
@cweijan I'm using CockroachDB CCL v25.1.2 (x86_64-pc-linux-gnu, built 2025/03/12 05:01:19, go1.22.8 X:nocoverageredesign).

**Comment by cweijan** [comment]
Hi @taylornoss , the latest version supports displaying table size for PostgreSQL, but CockroachDB is not compatible with it, so you need to change the connection type to CockroachDB.

<img width="1273" alt="Image" src="https://github.com/user-attachments/assets/89015994-d91e-4d89-86ab-810031b9189d" />

**Comment by taylornoss** [comment]
Ahh missed the additional options there. Upgrading and specifying that server type resolved the issue.

Thanks for the quick help!
