### ISSUE TITLE
[BUG] Activating extension failed

### ISSUE THREAD

**Issue by buzzzler** [cweijan/vscode-mysql#447]
- OS: Win 10 x64 21H2
- VSCode: 1.64.0-insider
- Description: Activating extension failed and as consequence "command 'mysql.connection.add' not found"
- DevTools Screenshot:

![issue](https://user-images.githubusercontent.com/3148923/150586001-c8cfe863-299f-41d2-861e-d5917b36811f.png)

**Comment by cweijan** [comment]
I have released multiple extensions with the same function, please check if the installation is duplicated.

**Comment by buzzzler** [comment]
Yes, I have only one of your extensions. For the experiment, I disabled all extensions except this one - cweijan.vscode-database-client2-4.5.2 and error is still there.

**Comment by cweijan** [comment]
Sorry this is really a bug, I have released version 4.5.3 to solve the problem.

**Comment by buzzzler** [comment]
Thanks a lot. Issue solved.
