### ISSUE TITLE
[BUG] - Unexpected code styling in varchar value

### ISSUE THREAD

**Issue by sraajboy** [cweijan/vscode-mysql#617]
- OS: Windows 7
- Database Type: MYSQL

I want to insert a varchar value with an apostrophe. Eg: ```D'arcy```, ```McDonald's```.
\
I escaped the single quote with another single quote like this ```D''arcy```.
It works fine as you can see in Line 7.
\
![image](https://user-images.githubusercontent.com/101339903/173361534-f3a3f311-da2e-456c-be0c-62c71d854ab6.png)
\
However when I escape the the single quote with a backslash ```D\'arcy```, 
it breaks the code styling.
\
![image](https://user-images.githubusercontent.com/101339903/173362103-4cc800ce-dd17-4994-a44a-90eb55047145.png)
\
And it assumes all the queries after it as a single block of code.
\
![image](https://user-images.githubusercontent.com/101339903/173363537-3c744841-60c7-4ad6-bd3f-f73266b767c5.png)
\
\
\
Also when I replace the single quote used to represent a string literal to double quotes,
the code styling is rectified while it still sees the rest of the code as a single block.
\
![image](https://user-images.githubusercontent.com/101339903/173370127-b616d752-699e-45ee-b661-ff6680356b1c.png)
<br/>
#### The SQL query works fine and the desired value ```D'arcy``` is inserted in the table in all cases.

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the feature.

**Comment by cweijan** [comment]
Hi, it has been fixed in the latest version 5.4.4.

**Comment by sraajboy** [comment]
Now it works fine.

But I found an additional case where this issue persists.

As seen in  Line 7,
When the string literal is represented using double quotes, one doesn't have to explicitly escape a single quote.

![image](https://user-images.githubusercontent.com/101339903/174739641-db68fad9-d335-43ae-804f-30c310a3ab19.png)

\
And the converse is also true. (i.e) when the string literal is represented using single quotes, one doesn't have to explicitly escape a double quote.

![image](https://user-images.githubusercontent.com/101339903/174740128-dec59b16-eb19-4b8d-861e-9e3434767e49.png)

\
In both the cases, the code styling works fine while it still sees the rest of the code as a single block.
<br/>

#### The SQL query works fine and the values, ```D'arcy``` and ```D"arcy``` respectively are inserted into the table.

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Hi, I have fixed this in version 5.4.7.

**Comment by sraajboy** [comment]
Everything works fine.

Except for one more case.

\
When the string literal is represented using double quotes and I want to insert a string containing a double quote, for example ```D"arcy```.

I escape the double quote with another double quote like this ```D""arcy```.
It works fine as you can see in Line 7.

![image](https://user-images.githubusercontent.com/101339903/175488532-8b7aa39a-fbc5-453f-96d8-64b5ec13bc52.png)

However when I escape the the double quote with a backslash ```D\"arcy```,
it breaks the code styling.

![image](https://user-images.githubusercontent.com/101339903/175489166-ec30ee28-c01c-43d9-910c-682263d69576.png)
<br/>

#### The SQL query works fine and the desired value ```D"arcy``` is inserted into the table in both cases.

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in the latest released version 5.5.0.

**Comment by sraajboy** [comment]
Everything works fine just the way it should.

Hence closing the issue.
